# Generated by Django 6.0.2 on 2026-02-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
