# Generated by Django 6.0.2 on 2026-02-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
