# Generated by Django 6.0.2 on 2026-02-19 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                default="events/default_event.jpg", upload_to="events/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="rsvp_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
